services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "43306:3306"
    volumes:
      - volume_mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    tty: true

  web:
    container_name: fastapi-container
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  volume_mysql:
    external: true
    name: volume-mysql
