services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app

volumes:
  db_data:
